# Generated by Django 3.2.16 on 2023-02-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                ("bike", models.CharField(max_length=100, verbose_name="Мотик")),
                ("phone", models.CharField(max_length=30, verbose_name="Телефон")),
                ("comment", models.TimeField(verbose_name="Комментарий")),
                (
                    "order_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата заявки"),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
    ]
