# Generated by Django 3.2.17 on 2023-02-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0003_auto_20230203_2239"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-order_date",),
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="bike",
            field=models.CharField(
                help_text="Мотоцикл", max_length=30, verbose_name="Мотик"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Расскажите, что Вы ожидаете от прошивки",
                null=True,
                verbose_name="Комментарий",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="name",
            field=models.CharField(help_text="Имя", max_length=30, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(
                help_text="Телефон", max_length=30, verbose_name="Телефон"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("name", "bike", "phone"), name="unique_order"
            ),
        ),
    ]
