version: '3.3'
services:


  app:
    build:
      context: .
      dockerfile: infra/Dockerfile
    restart: always
    volumes:
      - static_value:/app/static/
#      - media_value:/app/media/
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:80"
    volumes:
      - ./infra/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
#      - media_value:/var/html/media/
    depends_on:
      - app
volumes:
  static_value:
#  media_value:
